require("user.impatient")

-- core
require("user.options")
require("user.colorscheme")
require("user.keymaps")
require("user.autocommands")

-- plugins
require("user.plugins")
require("user.autopairs")
require("user.indent")
require("user.treesitter")
require("user.colorizer")
require("user.comment")
require("user.telescope")
require("user.toggleterm")
require("user.bufferline")
require("user.lualine")
require("user.dressing")
require("user.nvimtree")
require("user.zen")
require("user.lsp")
require("user.dap-configs")
require("user.luasnip")
require("user.cmp")
require("user.gitsigns")
require("user.hop")
